deployment:
  targets:
    - name: "stopify.fr"
      URL: "http://stopify-20210716100926442700000001.s3-website.eu-west-3.amazonaws.com"

  matchers:
      # Cache static assets for 20 years.
      - pattern: "^.+\.(js|css|png|jpg|gif|svg|ttf)$"
        cacheControl: "max-age=630720000, no-transform, public"
        gzip: true

      - pattern: "^.+\.(html|xml|json)$"
        gzip: true
