name: Hugo S3

# This is a basic workflow to help you get started with Actions

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches:
      - main

jobs:
Build_and_Deploy:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

    # Sets up Hugo
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
                hugo-version: '0.85.0'

# Builds chrisjburns.com repo
        - name: Build
          run: hugo --minify


     # Deploys built website to S3
        - name: Deploy to S3
          run: hugo deploy --force --maxDeletes -1 --invalidateCDN --config=./website/config/s3/configs3.yaml --themesDir=./website/themes
          env:
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                AWS_REGION: 'eu-west-2'
