name: S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
                hugo-version: '0.85.0'
                extended: true

        - name: Build
          run: hugo --minify -e s3 -s website

        - name: Deploy to S3
          run: hugo deploy --force --maxDeletes -1 -e s3 -s website
          env:
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
