name: S3

# This is a basic workflow to help you get started with Actions

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

    # Sets up Hugo
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
                hugo-version: '0.85.0'
                extended: true

# Builds chrisjburns.com repo
        - name: Build
          run: hugo --minify -e s3 -s website


     # Deploys built website to S3
        - name: Deploy to S3
          run: hugo deploy --force --maxDeletes -1 -e s3 -s website
          env:
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
